/*
VRP API

             Welcome to the Solvice API! You can use our API to access Solvice API endpoints,             which can get information on your solved jobs,             their statuses and of course post new solve jobs.         

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobAssignmentScoreExplanation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobAssignmentScoreExplanation{}

// JobAssignmentScoreExplanation Unresolved constraints in this alternative solution
type JobAssignmentScoreExplanation struct {
	// Constraint type.
	Constraint OnrouteConstraint `json:"constraint"`
	// Score impact of this conflict.
	Score string `json:"score"`
}

type _JobAssignmentScoreExplanation JobAssignmentScoreExplanation

// NewJobAssignmentScoreExplanation instantiates a new JobAssignmentScoreExplanation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobAssignmentScoreExplanation(constraint OnrouteConstraint, score string) *JobAssignmentScoreExplanation {
	this := JobAssignmentScoreExplanation{}
	this.Constraint = constraint
	this.Score = score
	return &this
}

// NewJobAssignmentScoreExplanationWithDefaults instantiates a new JobAssignmentScoreExplanation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobAssignmentScoreExplanationWithDefaults() *JobAssignmentScoreExplanation {
	this := JobAssignmentScoreExplanation{}
	return &this
}

// GetConstraint returns the Constraint field value
func (o *JobAssignmentScoreExplanation) GetConstraint() OnrouteConstraint {
	if o == nil {
		var ret OnrouteConstraint
		return ret
	}

	return o.Constraint
}

// GetConstraintOk returns a tuple with the Constraint field value
// and a boolean to check if the value has been set.
func (o *JobAssignmentScoreExplanation) GetConstraintOk() (*OnrouteConstraint, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Constraint, true
}

// SetConstraint sets field value
func (o *JobAssignmentScoreExplanation) SetConstraint(v OnrouteConstraint) {
	o.Constraint = v
}

// GetScore returns the Score field value
func (o *JobAssignmentScoreExplanation) GetScore() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *JobAssignmentScoreExplanation) GetScoreOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *JobAssignmentScoreExplanation) SetScore(v string) {
	o.Score = v
}

func (o JobAssignmentScoreExplanation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobAssignmentScoreExplanation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["constraint"] = o.Constraint
	toSerialize["score"] = o.Score
	return toSerialize, nil
}

func (o *JobAssignmentScoreExplanation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"constraint",
		"score",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobAssignmentScoreExplanation := _JobAssignmentScoreExplanation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobAssignmentScoreExplanation)

	if err != nil {
		return err
	}

	*o = JobAssignmentScoreExplanation(varJobAssignmentScoreExplanation)

	return err
}

type NullableJobAssignmentScoreExplanation struct {
	value *JobAssignmentScoreExplanation
	isSet bool
}

func (v NullableJobAssignmentScoreExplanation) Get() *JobAssignmentScoreExplanation {
	return v.value
}

func (v *NullableJobAssignmentScoreExplanation) Set(val *JobAssignmentScoreExplanation) {
	v.value = val
	v.isSet = true
}

func (v NullableJobAssignmentScoreExplanation) IsSet() bool {
	return v.isSet
}

func (v *NullableJobAssignmentScoreExplanation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobAssignmentScoreExplanation(val *JobAssignmentScoreExplanation) *NullableJobAssignmentScoreExplanation {
	return &NullableJobAssignmentScoreExplanation{value: val, isSet: true}
}

func (v NullableJobAssignmentScoreExplanation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobAssignmentScoreExplanation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


