/*
VRP API

             Welcome to the Solvice API! You can use our API to access Solvice API endpoints,             which can get information on your solved jobs,             their statuses and of course post new solve jobs.         

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CustomDistanceMatrices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomDistanceMatrices{}

// CustomDistanceMatrices Custom distance matrix configuration for multi-profile and multi-slice scenarios
type CustomDistanceMatrices struct {
	// Map of vehicle profile names (CAR, BIKE, TRUCK) to time slice hour mappings. Each time slice hour maps to a matrix ID that should be fetched from the distance matrix service. Time slice hours correspond to: 6=MORNING_RUSH, 9=MORNING, 12=MIDDAY, 14=AFTERNOON, 16=EVENING_RUSH, 20=NIGHT.
	ProfileMatrices map[string]map[string]string `json:"profileMatrices,omitempty"`
	// Optional URL for external distance matrix service endpoint. If not provided, uses the default system service.
	MatrixServiceUrl NullableString `json:"matrixServiceUrl,omitempty"`
}

// NewCustomDistanceMatrices instantiates a new CustomDistanceMatrices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomDistanceMatrices() *CustomDistanceMatrices {
	this := CustomDistanceMatrices{}
	return &this
}

// NewCustomDistanceMatricesWithDefaults instantiates a new CustomDistanceMatrices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomDistanceMatricesWithDefaults() *CustomDistanceMatrices {
	this := CustomDistanceMatrices{}
	return &this
}

// GetProfileMatrices returns the ProfileMatrices field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomDistanceMatrices) GetProfileMatrices() map[string]map[string]string {
	if o == nil {
		var ret map[string]map[string]string
		return ret
	}
	return o.ProfileMatrices
}

// GetProfileMatricesOk returns a tuple with the ProfileMatrices field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomDistanceMatrices) GetProfileMatricesOk() (*map[string]map[string]string, bool) {
	if o == nil || IsNil(o.ProfileMatrices) {
		return nil, false
	}
	return &o.ProfileMatrices, true
}

// HasProfileMatrices returns a boolean if a field has been set.
func (o *CustomDistanceMatrices) HasProfileMatrices() bool {
	if o != nil && !IsNil(o.ProfileMatrices) {
		return true
	}

	return false
}

// SetProfileMatrices gets a reference to the given map[string]map[string]string and assigns it to the ProfileMatrices field.
func (o *CustomDistanceMatrices) SetProfileMatrices(v map[string]map[string]string) {
	o.ProfileMatrices = v
}

// GetMatrixServiceUrl returns the MatrixServiceUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomDistanceMatrices) GetMatrixServiceUrl() string {
	if o == nil || IsNil(o.MatrixServiceUrl.Get()) {
		var ret string
		return ret
	}
	return *o.MatrixServiceUrl.Get()
}

// GetMatrixServiceUrlOk returns a tuple with the MatrixServiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomDistanceMatrices) GetMatrixServiceUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MatrixServiceUrl.Get(), o.MatrixServiceUrl.IsSet()
}

// HasMatrixServiceUrl returns a boolean if a field has been set.
func (o *CustomDistanceMatrices) HasMatrixServiceUrl() bool {
	if o != nil && o.MatrixServiceUrl.IsSet() {
		return true
	}

	return false
}

// SetMatrixServiceUrl gets a reference to the given NullableString and assigns it to the MatrixServiceUrl field.
func (o *CustomDistanceMatrices) SetMatrixServiceUrl(v string) {
	o.MatrixServiceUrl.Set(&v)
}
// SetMatrixServiceUrlNil sets the value for MatrixServiceUrl to be an explicit nil
func (o *CustomDistanceMatrices) SetMatrixServiceUrlNil() {
	o.MatrixServiceUrl.Set(nil)
}

// UnsetMatrixServiceUrl ensures that no value is present for MatrixServiceUrl, not even an explicit nil
func (o *CustomDistanceMatrices) UnsetMatrixServiceUrl() {
	o.MatrixServiceUrl.Unset()
}

func (o CustomDistanceMatrices) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomDistanceMatrices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ProfileMatrices != nil {
		toSerialize["profileMatrices"] = o.ProfileMatrices
	}
	if o.MatrixServiceUrl.IsSet() {
		toSerialize["matrixServiceUrl"] = o.MatrixServiceUrl.Get()
	}
	return toSerialize, nil
}

type NullableCustomDistanceMatrices struct {
	value *CustomDistanceMatrices
	isSet bool
}

func (v NullableCustomDistanceMatrices) Get() *CustomDistanceMatrices {
	return v.value
}

func (v *NullableCustomDistanceMatrices) Set(val *CustomDistanceMatrices) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomDistanceMatrices) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomDistanceMatrices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomDistanceMatrices(val *CustomDistanceMatrices) *NullableCustomDistanceMatrices {
	return &NullableCustomDistanceMatrices{value: val, isSet: true}
}

func (v NullableCustomDistanceMatrices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomDistanceMatrices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


